### ISSUE TITLE
sbt-sass not working with sbt-digest

### ISSUE THREAD

**Issue by biegel** [ShaggyYeti/sbt-sass#11]
We've installed sbt-digest (https://github.com/sbt/sbt-digest) into our project, but it looks like it's hashing the precompiled `.scss` files instead of the final output `.css` files.

Running a `find . -name "*.md5"` in our `target` directory shows dozens of our scss files, e.g.:

```
./web/digest/styles/components/listicle.scss.md5
./web/digest/styles/components/main_nav.scss.md5
./web/digest/styles/components/masthead.scss.md5
./web/digest/styles/components/most_popular.scss.md5
```

**Comment by ShaggyYeti** [comment]
Hello.
I could not repeat described error.
I installed sbt-digest into [play-sass-example](https://github.com/ShaggyYeti/sbt-sass/tree/master/play-sass-example) project and executed `activator stage`
The result of `find ./target/web/digest/. -name *.css`

```
./target/web/digest/./css/d41d8cd98f00b204e9800998ecf8427e-main.css
./target/web/digest/./lib/normalize.css
./target/web/digest/./lib/normalize.css/836625e5ecabdada6dd84787e0f72a16-normalize.css
./target/web/digest/./lib/foundation/css/46ddb23e41b8ab14343d31dabbd0beb7-foundation.css
./target/web/digest/./lib/foundation/css/ee9b8f5024ef0fc2fedadf7514f040cf-foundation.min.css
./target/web/digest/./abc/d792c37acafb5dbbe8d536dae28612ca-test.css
./target/web/digest/./abc/afbe9ee27eaf1c032be05fb604f2d990-test2.css
./target/web/digest/./abc/85cb36cd0128df7219108ee9dbeb73a8-test.min.css
./target/web/digest/./abc/e7d71ff9ca5129a1ab788d67e1c507df-test2.min.css
```

The result of `find ./target/web/. -name *.css.md5`

```
./target/web/./digest/css/main.css.md5
./target/web/./digest/lib/normalize.css/normalize.css.md5
./target/web/./digest/lib/foundation/css/foundation.css.md5
./target/web/./digest/lib/foundation/css/foundation.min.css.md5
./target/web/./digest/abc/test2.min.css.md5
./target/web/./digest/abc/test.min.css.md5
./target/web/./digest/abc/test2.css.md5
./target/web/./digest/abc/test.css.md5
```

Could you describe your situation in details. Which version of sbt-sass plugin did you use? Did you use `includeFilter in digest` [parameter](https://github.com/sbt/sbt-digest#filters)?

**Comment by biegel** [comment]
So I took a look at your `project/plugins.sbt`.  The only difference is that your test project uses `sbt-plugin` version `2.3.0` and we are using `2.3.4`.  I tried downgrading with the same result.

I have narrowed the problem down to the `sbt-rjs` plugin we are also using.  When sbt-rjs is enabled, the hashes for the `.css` files are not created (but they run on the `.scss` files).

I have confirmed this behavior in your test project as well.  You can reproduce by using this `build.sbt` and `project/plugins.sbt`:

build.sbt:

```
name := """play-sass-example"""

version := "1.0-SNAPSHOT"

sassOptions in Assets ++= Seq("--compass", "-r", "compass")

lazy val root = (project in file(".")).enablePlugins(PlayJava)

pipelineStages := Seq(rjs, digest)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  "org.webjars" %% "webjars-play" % "2.3.0",
  "org.webjars" % "foundation" % "5.3.0",
  javaJdbc,
  javaEbean,
  cache,
  javaWs
)
```

project/plugins.sbt:

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.0")

resolvers += Resolver.url("GitHub repository", url("http://shaggyyeti.github.io/releases"))(Resolver.ivyStylePatterns)

addSbtPlugin("default" % "sbt-sass" % "0.1.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.5")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")
```

I don't know enough about what's happening under the hood to know if this is a problem with sbt-sass or sbt-rjs.  `find . -name *.css.md5` will return no results.

**Comment by huntc** [comment]
I've raised PR https://github.com/ShaggyYeti/sbt-sass/pull/13 tidying up a few things - it'd be interesting to see if our problems here are addressed. If not, I can look further.

**Comment by ShaggyYeti** [comment]
Seems that problem solved due to patch #13. Please check it in your project with sbt-sass v0.1.7.

**Comment by biegel** [comment]
Yes, everything works great now!  Thank you @huntc and @ShaggyYeti.

**Comment by ShaggyYeti** [comment]
Thank you too. :)
