### ISSUE TITLE
Sourcemap option warning with Sass 3.4.0 (Selective Steve)

### ISSUE THREAD

**Issue by acjay** [ShaggyYeti/sbt-sass#12]
I'm getting the following warning in my SBT output:

```
[error] Sass compiler: DEPRECATION WARNING: Passing --sourcemap without a value is deprecated.
```

But I only get it if there's a fatal compilation error. I think output of the warning is suppressed if there are no compilation errors. (That could be a separate issue worth noting.)

**Comment by ShaggyYeti** [comment]
Fixed this issue in 0.1.7 version. Now sass should be >= v3.4.0
