### ISSUE TITLE
changes in .scss files with @import directive are not compiled on the fly

### ISSUE THREAD

**Issue by clescot** [ShaggyYeti/sbt-sass#14]
Hi,
it seems that changes on files directly referenced in your scala templates are compiled on the fly.
But files imported with @import directive, are not recompiled.
I've tested this issue also on the play-sass-example project, by running the project with:
   `activator ~run`
and changed the _a.scss file without any effect on the generated test.css.
I've also tried to activate the  sass-globbing pluging way, without success.
Have you any clue to  solve my issue? 

Best regards,

Charles.
ps: i've tested this use case with the jlitolas plugin, and it works ; but the jlitolas plugin does not handle the webjars feature like your plugin.

**Comment by ShaggyYeti** [comment]
Hello.
I Agree. Incremental compilation has broken for imported files with names that starts with `_`. Fixed in `v0.1.8`. Write to me if it will not work.
Thank you for your bug report.

**Comment by clescot** [comment]
Hello,
thanks a lot for your quick support!
Your fix unblocks my use case.
Nevertheless, it remains a minor annoyance : 
I need to change firstly (and only one time), the file which import the partial scss file, to 'activate' Incremental compilation of the partial scss file (which starts with _).
After the first change, in the test.scss in the play-sass-example, all change in _a.scss are compiled automatically ; but if i change directly _a.scss, and not change the test.scss firstly, the resulting test.css file is not changed.

Many thanks for your great plugin.

Charles.

**Comment by ShaggyYeti** [comment]
> After the first change, in the test.scss in the play-sass-example, all change in _a.scss are compiled automatically ; but if i change directly _a.scss, and not change the test.scss firstly, the resulting test.css file is not changed.

Yes, i repeated this use case in `v0.1.7`. 

In new version (`v0.1.8`) the problem is fixed. Now when you change one (`_a.scss` for example) of these files, plugin triggers compilation of all dependent files (`test.scss`) from this one. 

Does the new version work properly in your case?

> Many thanks for your great plugin

Thank you :)

**Comment by clescot** [comment]
Hi,
my second report was refering to the v0.1.8 version and not the 0.1.7 one.
i've double checked the sbt-sass version used on my computer.
But i admit this bug seems odd : i've retested the use case on another computer, and....it works.

best regards,

Charles.

**Comment by ShaggyYeti** [comment]
> my second report was refering to the v0.1.8 version and not the 0.1.7 one.
> i've double checked the sbt-sass version used on my computer.

Seems that the reason is in old cache files. Try to execute `activator clean` and then `activator ~run`. It should help.

**Comment by clescot** [comment]
Hi,
you're right : 
activator clean before activator ~run solve my issue !

thanks a lot!

Charles.
