### ISSUE TITLE
Unable to download sbt-sass plugin. Invalid sha1

### ISSUE THREAD

**Issue by wadum** [ShaggyYeti/sbt-sass#2]
While trying to run activator i get the following error

[warn] problem while downloading module descriptor: http://shaggyyeti.github.io/releases/default/sbt-sass/scala_2.10/sbt
_0.13/0.1.1/ivys/ivy.xml: invalid sha1: expected=40c0b057be365661a681923a2d9406c874030d00 computed=0f5dac9c33e69b6502944
905c878e8e3e6b5750a (401ms)

**Comment by kritzikratzi** [comment]
same here

**Comment by TheRusskiy** [comment]
+1

**Comment by ShaggyYeti** [comment]
fixed
