### ISSUE TITLE
Unable to obtain css using Stage and Dist command for Play

### ISSUE THREAD

**Issue by jonandersen** [ShaggyYeti/sbt-sass#4]
The plugin in works in devlopment mode but when I run the stage command the css file can't be loaded.

Link in main.html:

```
  <link rel="stylesheet" href="@routes.Assets.versioned("stylesheets/base.css")" data-required="true">
```

build.sbt:

```
sassOptions in Assets ++= Seq("--compass", "-r", "compass")

sassPublicDir in Assets := "stylesheets"
```

Structure: public/stylesheets/base.scss

The files are correctly compiled when running the stage command and they can be found inside the assets jar but can't be loaded.

The provided example is crashing with a runtime exception when running the stage command. 

Any ideas what to do?

Also why is the folder change from assets -> public ? 
http://www.playframework.com/documentation/2.3.0/Anatomy
Suggest having an assets/stylesheets folder with the less/scss files

**Comment by ShaggyYeti** [comment]
The problem fixed.

> Also why is the folder change from assets -> public ? 

It was wrong solution. Now `assets` is turned back instead of `public`.
