### ISSUE TITLE
Files get compiled repeatedly

### ISSUE THREAD

**Issue by DylanArnold** [ShaggyYeti/sbt-sass#5]
I'm trying out your plugin with an existing project after upgrading to play 2.3.1 however I immediately noticed very slow requests to the play server, 10 seconds plus, making it unusable. 

I copied the plugin into my project and added a println statement inside the SbtSass plugin where the css is written with IO.write . This gets called repeatedly and never ends.

I'm investigating more but it would be nice to know if others are experiencing this. I'm trying to debug it but I'm completely new to sbt-web so don't have any ideas yet.

I noticed other plugins write some output to the console so it would be nice if sbt-sass did that too so it would be more obvious that this is happening.

Thanks for the plugin (and any help).

**Comment by ShaggyYeti** [comment]
I agree. I found this error yesterday. The plugin recompiles for each assets request (every css and js file). I'm working on a fix now.

thanks for your feedback :-)

**Comment by DylanArnold** [comment]
Thanks! :)
