### ISSUE TITLE
Add ability configure where compiled CSS files go

### ISSUE THREAD

**Issue by ilanbiala** [ShaggyYeti/sbt-sass#7]
I'd like to choose where the files go, can you add that option?

**Comment by ShaggyYeti** [comment]
Hello.
This plugin is based on `sbt-web` and gets output directory from its variable `webTarget in Assets`. The result of sass-files compilation creates in `(webTarget in Assets).value / "sass" / "main"`. Then generated css-files copies into jar-file (if u execute `activator stage`) or into `<project folder>/target/web/public/main` (if u execute `activator run`). This approach is standard for sbt-web: https://github.com/sbt/sbt-web

I would like to save the compliance with sbt-web workflow.

Tell me please, how you want to use this option (in common words)? And I will find solution.

**Comment by ilanbiala** [comment]
Ideally, I want to have a folder in `app/` called `assets/`. `assets/` contains precompiled files, and compiled files would be stored where all my other compiled/not necessary to compile assets are stored, in `public/`. So something like `assets/scss/` -> `public/css/`

**Comment by acjay** [comment]
@ilanbiala That's not very Play-ish. You can do this, but you might find yourself fighting the "magic" of the sane defaults all the way down the line. If you're compiling things outside the sbt-web workflow, you should keep them out of `app/`, and in `public/` instead. If you want to go fully manual, you might find the task I wrote in #8 helpful. My project converted to sbt-sass to try to better align with sbt-web, though.

**Comment by ShaggyYeti** [comment]
@ilanbiala I think that it's realizable by sbt-web pipelineStage. But i need some time to code it. Probably it should be a separate sbt-plugin for assets mapping.

**Comment by ilanbiala** [comment]
@ShaggyYeti is this going to happen, or should I just close the issue?

**Comment by tindzk** [comment]
It is already possible to set a target directory for the CSS files:

``` scala
resourceManaged in sass in Assets := cssPath
```

I described it [here](https://github.com/widok/widok/blob/master/docs/chapters/03-build-process.md#configure-paths) in more detail.
