### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by acjay** [ShaggyYeti/sbt-sass#8]
A project I'm on just recently converted to sbt-sass after relying on a custom-written task for a while. sbt-sass is vastly underperforming. It takes about a minute to compile our 16 sass files, when it used to be a few seconds. We use the Susy grid framework, which is included by most of the files we compile. Any ideas for how we can speed sbt-sass up?

Here is the task we used to use, for reference:

```

val sassTask = taskKey[Seq[File]]("Compiles Sass files")

val sassOutputDir = settingKey[File]("Output directory for Sass generated files")

val sassLibDirs = settingKey[Seq[File]]("Directories for Sass library includes")

sassOutputDir := target.value / "web" / "sass" / "main"

sassLibDirs := Seq(
  target.value / "web" / "web-modules" / "main" / "webjars" / "lib" / "susy" / "sass"
)

resourceDirectories in Assets += sassOutputDir.value

sassTask := {
  val x = (WebKeys.nodeModules in Assets).value // to depend on Webjars being installed before building Sass
  val sourceDir = (sourceDirectory in Assets).value
  val outputDir = sassOutputDir.value
  val sourceFiles = (sourceDir ** "*.scss").get
  val includes = sassLibDirs.value map (_.toString) flatMap { Seq("-I", _) }
  (Seq("sass", "--update") ++ includes ++ Seq(s"$sourceDir:$outputDir")).!
  (outputDir ** "*.css").get
}

sourceGenerators in Assets <+= sassTask
```

**Comment by acjay** [comment]
@ShaggyYeti Please let me know if you have any advice. We will need to switch back to my ad hoc SBT task or another Sass solution if there's no info on what's causing the slowness and no way to address it.

If it's any help, every time I change one `.scss` file, it says it's compiling all 16 files, so it seems like it may not be tracking unchanged files correctly.

**Comment by ShaggyYeti** [comment]
Hello. I was on summer holiday. :)

So, in my project plugin compiles 33 files 1-2 sec.

> so it seems like it may not be tracking unchanged files correctly.

I'll check code today.

**Comment by ShaggyYeti** [comment]
Seems that problem has fixed. Check it please with new version `0.1.4`

**Comment by acjay** [comment]
Lovely, thanks!

**Comment by ShaggyYeti** [comment]
Does it work properly?

**Comment by acjay** [comment]
Indeed it does! Changes to individual SCSS files only take a second or so to recompile. It's great, thanks!

**Comment by ShaggyYeti** [comment]
Great! You're welcome.
