### ISSUE TITLE
Webjars Integration

### ISSUE THREAD

**Issue by Voltir** [ShaggyYeti/sbt-sass#9]
I would like to be able to include a webjar such as the Foundation libraries in a Play 2.3 project. 

I have an app.scss in the assets/stylesheet directory and I am attempting to import the foundation scss library from the foundation webjar. According to http://www.playframework.com/documentation/2.3.x/AssetsLess when working with less, I should be able to do something like @import "lib/bootstrap/less/bootstrap.less";

I would equivelently like to be able to do @import "lib/foundation/scss/foundation" but I have been unable to get that to work -- As a workaround, I am currently copying the scss files of foundation into the assets/stylesheets directory.

**Comment by acjay** [comment]
@Voltir  My project uses a Susy grid library webjar we created, and we use the sbt-sass options to set a SASS include directory thusly:

```
val sassLibDirs = settingKey[Seq[File]]("Directories for Sass library includes")

// Tell sbt-sass to look for files in the following paths
sassLibDirs := Seq(
  target.value / "web" / "web-modules" / "main" / "webjars" / "lib" / "susy" / "sass"
)

// Append the directories via the command line option "-I"
// See: https://github.com/ShaggyYeti/sbt-sass
sassOptions in Assets ++= sassLibDirs.value map (_.toString) flatMap { Seq("-I", _) }

// Make webjars a dependency for sass compilation
sass in Assets <<= (sass in Assets) dependsOn (WebKeys.nodeModules in Assets)
```

It feel pretty hacky, but it works fine for us and may work for you too. I'd be glad to know whether there is a more idiomatic way of accomplishing this, and if there isn't, request for there to be one.

**Comment by ShaggyYeti** [comment]
Done. Please change plugin version to 0.1.5 and check. Does it work?

P.S. Also, project in `play-sass-example` in this repo has an example of usage sbt-sass with webjars
